// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { ignaiChatbotBlock } from '.'

export const ignaiChatbotBlockSchema = parseBlockSchema(ignaiChatbotBlock)
export const ignaiChatbotCredentialsSchema =
  parseBlockCredentials(ignaiChatbotBlock)
